import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: {
    default: 'Next.js tutorial - Codevolution',
    template: '%s | Codevolution'
  },
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex h-screen w-full flex-col bg-blue-50'>
          <Navbar />
          <main className='border-md mx-auto h-full w-5xl flex-1 border bg-green-50 p-3'>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
